### ISSUE TITLE
>xbuild MultyNetHack/MultyNetHack.sln

### ISSUE THREAD

**Issue by ghost** [branc116/MultyNetHack#4]
The current README does not tell me what to do afterwards.

Please add more instruction in how to get this to run.

I compiled mono from source and this worked fine.

I also did the xbuild etc... .sln part.

> xbuild MultyNetHack/MultyNetHack.sln
## Output was:

XBuild Engine Version 14.0  
Mono, Version 4.4.2.0  
Copyright (C) 2005-2013 Various Mono authors                                                                                                                                                  

Build started 31.07.2016 18:58:13.                                                                                                                                                            

---

Project "/Depot/Downloads/MultyNetHack-master/MultyNetHack/MultyNetHack.sln" (default target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "Debug|Any CPU".
        Target Build:
                Project "/Depot/Downloads/MultyNetHack-master/MultyNetHack/MultyNetHack/MultyNetHack.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: Debug Platform: AnyCPU
                                Created directory "bin/Debug/"
                                Created directory "obj/Debug/"
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target CoreCompile:
                                Tool /Programs/Mono/4.4.2.8/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /debug+ /optimize- /out:obj/Debug/MultyNetHack.exe Commands/BaseCommand.cs Commands/GeneratePathCommand.cs Commands/GenerateRoomsCommand.cs Commands/MoveCommand.cs Commands/ScrollCommand.cs Componets.cs DebugItems/DebugMessage.cs Screen/DebugScreen.cs Screen/EngineScreen.cs Screen/MainMenuScreen.cs Controls.cs Engine.cs Enums.cs Screen/HelpScreen.cs Math.cs Program.cs Properties/AssemblyInfo.cs Screen/Screen.cs UIComponents/Button.cs obj/Debug/.NETFramework,Version=v4.6.1.AssemblyAttribute.cs /target:exe /define:"DEBUG;TRACE" /nostdlib /platform:AnyCPU /reference:/Programs/Mono/4.4.2.8/lib/mono/4.5/System.dll /reference:/Programs/Mono/4.4.2.8/lib/mono/4.5/System.Drawing.dll /reference:/Programs/Mono/4.4.2.8/lib/mono/4.5/System.Net.dll /reference:/Programs/Mono/4.4.2.8/lib/mono/4.5/System.Web.Extensions.dll /reference:/Programs/Mono/4.4.2.8/lib/mono/4.5/System.Xml.Linq.dll /reference:/Programs/Mono/4.4.2.8/lib/mono/4.5/System.Data.DataSetExtensions.dll /reference:/Programs/Mono/4.4.2.8/lib/mono/4.5/Microsoft.CSharp.dll /reference:/Programs/Mono/4.4.2.8/lib/mono/4.5/System.Data.dll /reference:/Programs/Mono/4.4.2.8/lib/mono/4.5/System.Net.Http.dll /reference:/Programs/Mono/4.4.2.8/lib/mono/4.5/System.Xml.dll /reference:/Programs/Mono/4.4.2.8/lib/mono/4.5/System.Core.dll /reference:/Programs/Mono/4.4.2.8/lib/mono/4.5/mscorlib.dll /warn:4
Componets.cs(580,21): warning CS0219: The variable `temp' is assigned but its value is never used
Screen/EngineScreen.cs(180,18): warning CS0219: The variable`t' is assigned but its value is never used
Screen/EngineScreen.cs(145,34): warning CS0219: The variable `gRC' is assigned but its value is never used
Engine.cs(113,18): warning CS0219: The variable`t' is assigned but its value is never used
Program.cs(15,20): warning CS0219: The variable `e' is assigned but its value is never used
Componets.cs(28,24): warning CS0414: The private field`MultyNetHack.Component.mRand' is assigned but its value is never used
Screen/EngineScreen.cs(29,43): warning CS0067: The event `MultyNetHack.Screen.EngineSceen.Message' is never used
Engine.cs(18,14): warning CS0414: The private field`MultyNetHack.Engine.SceenSize' is assigned but its value is never used
Math.cs(278,22): warning CS0169: The private field `MultyNetHack.LinearInterpolator.Values' is never used
                        Target _CopyAppConfigFile:
                                Copying file from '/Depot/Downloads/MultyNetHack-master/MultyNetHack/MultyNetHack/App.config' to '/Depot/Downloads/MultyNetHack-master/MultyNetHack/MultyNetHack/bin/Debug/MultyNetHack.exe.config'
                        Target DeployOutputFiles:
                                Copying file from '/Depot/Downloads/MultyNetHack-master/MultyNetHack/MultyNetHack/obj/Debug/MultyNetHack.exe.mdb' to '/Depot/Downloads/MultyNetHack-master/MultyNetHack/MultyNetHack/bin/Debug/MultyNetHack.exe.mdb'
                                Copying file from '/Depot/Downloads/MultyNetHack-master/MultyNetHack/MultyNetHack/obj/Debug/MultyNetHack.exe' to '/Depot/Downloads/MultyNetHack-master/MultyNetHack/MultyNetHack/bin/Debug/MultyNetHack.exe'
                Done building project "/Depot/Downloads/MultyNetHack-master/MultyNetHack/MultyNetHack/MultyNetHack.csproj".
Done building project "/Depot/Downloads/MultyNetHack-master/MultyNetHack/MultyNetHack.sln".

Build succeeded.

Warnings:

/Depot/Downloads/MultyNetHack-master/MultyNetHack/MultyNetHack.sln (default targets) ->
(Build target) ->  
/Depot/Downloads/MultyNetHack-master/MultyNetHack/MultyNetHack/MultyNetHack.csproj (default targets) ->  
/Programs/Mono/4.4.2.8/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->                                                                                              

```
    Componets.cs(580,21): warning CS0219: The variable `temp' is assigned but its value is never used
    Screen/EngineScreen.cs(180,18): warning CS0219: The variable `t' is assigned but its value is never used
    Screen/EngineScreen.cs(145,34): warning CS0219: The variable `gRC' is assigned but its value is never used
    Engine.cs(113,18): warning CS0219: The variable `t' is assigned but its value is never used
    Program.cs(15,20): warning CS0219: The variable `e' is assigned but its value is never used
    Componets.cs(28,24): warning CS0414: The private field `MultyNetHack.Component.mRand' is assigned but its value is never used
    Screen/EngineScreen.cs(29,43): warning CS0067: The event `MultyNetHack.Screen.EngineSceen.Message' is never used
    Engine.cs(18,14): warning CS0414: The private field `MultyNetHack.Engine.SceenSize' is assigned but its value is never used
    Math.cs(278,22): warning CS0169: The private field `MultyNetHack.LinearInterpolator.Values' is never used

     9 Warning(s)
     0 Error(s)
```

Time Elapsed 00:00:02.4379620

---

But now I have no idea what to do. Perhaps the README could mention what to do next.

Thanks.

**Comment by branc116** [comment]
Whell that is a standard steep, I didn't think it was worth mentioning, but ok.

You just write: >mono MultyNetHack/MultyNetHack/bin/Debug/MultyNetHack.exe

I'll add it to the readme. :)
