### ISSUE TITLE
camelCase in the README is written wrong

### ISSUE THREAD

**Issue by NicolasCARPi** [branc116/MultyNetHack#5]
Hello,

camelCase is written in camelCase :)
Also, you have a file named Componets.cs.

~Nico

**Comment by branc116** [comment]
Hi,

I don't understand. What is wrong about CamelCase in the readme?

And I have corrected a lot of spelling mistakes in the solution.

Point out more spelling mistakes, if you can find them, I'm unable to :)

Branc

**Comment by tlahmann** [comment]
**PascalCase** is when the first letter is capitalized.
**camelCase** is when the first letter is small.

https://msdn.microsoft.com/en-us/library/ms229043.aspx

**Comment by branc116** [comment]
Interesting, didn't know that...

Thanks for the info, I'll correct it :)

**Comment by branc116** [comment]
A good sir @tidusjar corrected it :)
